config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
	root 'home#index'

	resources :categories
	resources :news
	resources :tags

	get '/search' => 'search#index'
	get '/search/tag' => 'search#tag'

end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	friendly_id :alias, use: [:slugged, :finders]

	has_many :news

  def alias
    "#{name} - #{id}"
  end

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/news.rb
class News < ActiveRecord::Base
	extend FriendlyId
	friendly_id :alias, use: [:slugged, :finders]
	
	cattr_accessor :author
  belongs_to :user
  belongs_to :category
  has_many :news_tags
  has_many :tags, through: :news_tags, dependent: :destroy

  paginates_per 8

  has_attached_file :image, styles: { large: "855x395#", medium: "200x130#", thumb: "160x117#", small: "59x42#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  after_initialize do
    if new_record?
      self.user_id ||= self.author.id
    end
  end

  def alias
    "#{title} - #{id}"
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/news_tag.rb
class NewsTag < ActiveRecord::Base
  belongs_to :news
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :news_tags
  has_many :news, through: :news_tags, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :news

  has_attached_file :avatar, styles: { large: "300x300#", medium: "100x100#", small: "30x30#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :set_categories
  before_filter :set_author
  before_action :set_site_search

  private
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
    end

	  def set_categories
	    @categories = Category.all.order('id ASC')
	  end

    def set_author
       News.author = current_user
    end

	  def set_site_search
	    @search_in_site = News.ransack(params[:q])
	  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]
	before_action :set_news, only: [:show]

  def show
		@page_title = @category.name
		@page_description = @category.description
  end

  private

	  def set_category
	  	@category = Category.find(params[:id])
	  end

	  def set_news
	    @news = @category.news.order('id DESC').page params[:page]
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@breaking_news = News.order('id DESC').last(5)
		@economy = News.where(category_id: 2).order('id DESC').limit(11).to_a
		@breakingviews = News.where(category_id: 1).order('id DESC').limit(7)
		@travel = News.where(category_id: 9).order('id DESC').limit(6)
		@world = News.where(category_id: 4).order('id DESC').limit(6)
		@tags = NewsTag.joins(:tag).group(:name).limit(15).order('count_news_id DESC').count(:news_id)
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	before_action :set_news, only: [:show]

  def show
		@page_title = @news.title
		@page_description = @news.description
		@page_keywords = @news.tags.all.map{|a| a.name}.split(',')
		@related_news = News.where(category_id: @news.category).order('id DESC').limit(6)
  end

  private

	  def set_news
	  	@news = News.find(params[:id])
	  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		set_results( News.ransack(params[:q]) )
	end

	def tag
		set_results( News.ransack( tags_name_cont: params[:q]) )
		render "index"
	end

  def set_results(search)
    if search.nil?
      @results = []
    else
      @results = search.result(distinct: true).order('id DESC').page params[:page]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def last_news
		return News.last(6)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/application/_rightbar.html.erb
							<!-- BEGIN .widget -->
							<div class="widget">
								<h3>SOSYAL AĞLAR</h3>
								<div class="widget-social">
									<div class="social-bar">
										<a href="#" class="social-icon"><i class="number">1.2m</i><span class="facebook">Facebook</span></a>
										<a href="#" class="social-icon"><i class="number">2.6k</i><span class="twitter">Twitter</span></a>
										<a href="#" class="social-icon"><i class="number">1.4k</i><span class="google">Google+</span></a>
										<a href="#" class="social-icon"><i class="number">823</i><span class="linkedin">Linkedin</span></a>
									</div>
									<p>Sosyal Ağlar üzerinden bizi takip ederek en güncel haberlere ulaşın.</p>
								</div>
							<!-- END .widget -->
							</div>
							
							<!-- BEGIN .widget -->
							<div class="widget">
								<h3>Son Haberler</h3>
								<div class="widget-articles">
									<ul>
										<% last_news.each do |news| %>
										<li>
											<div class="article-photo">
								        <%= link_to news_path(news), class: 'hover-effect' do %>
								          <%= image_tag news.image.url(:small), alt: news.title %>
								        <% end %>
											</div>
											<div class="article-content">
												<h4><%= link_to truncate(news.title, length: 60, omission: '...'), news_path(news) %>
													<a href="#" class="h-comment">201</a></h4>
												<span class="meta">
													<a href="#"><span class="icon-text">&#128340;</span><%= news.created_at.to_formatted_s(:nice) %></a>
												</span>
											</div>
										</li>
										<% end %>
									</ul>
								</div>
							<!-- END .widget -->
							</div>
							
							<!-- BEGIN .widget -->
							<div class="widget">
								<h3>Son Yorumlar</h3>
								<div class="widget-comments">
									<ul>
										<li>
											<div class="comment-photo">
												<span class="hover-effect"><img src="/assets/allegro/photos/avatar-1.jpg" alt="" /></span>
											</div>
											<div class="comment-content">
												<h3>Bran Sabas</h3>
												<p>Suscipit partiendo comprehensam ne eos mel, nam omnis maiestatis no. Eum at reformidans ius, cu sonet tollit mea</p>
												<span class="meta">
													<a href="post.html"><span class="icon-text">&#59212;</span>View Article</a>
												</span>
											</div>
										</li>
										<li>
											<div class="comment-photo">
												<a href="#" class="hover-effect"><img src="/assets/allegro/photos/avatar-2.jpg" alt="" /></a>
											</div>
											<div class="comment-content">
												<h3><a href="#">Orange-Themes</a></h3>
												<p>Sed primis voluptaria voluptatum et, cum ex accusam fierent honestatis. Duo illum saperet no. Errem verterem legendos eu.</p>
												<span class="meta">
													<a href="post.html"><span class="icon-text">&#59212;</span>View Article</a>
												</span>
											</div>
										</li>
										<li>
											<div class="comment-photo">
												<span class="hover-effect"><img src="/assets/allegro/photos/avatar-3.jpg" alt="" /></span>
											</div>
											<div class="comment-content">
												<h3>Spencer Abner</h3>
												<p>Cu malorum molestiae intellegat qui. Molestiae hendrerit cu his.</p>
												<span class="meta">
													<a href="post.html"><span class="icon-text">&#59212;</span>View Article</a>
												</span>
											</div>
										</li>
									</ul>
								</div>
							<!-- END .widget -->
							</div>

app/views/categories/show.html.erb
			<!-- BEGIN .content -->
			<div class="content">
				
				<!-- BEGIN .wrapper -->
				<div class="wrapper">
					
					<div class="ad-banner">
						<a href="contact-us.html" class="ad-link top"><span class="icon-text">&#9662;</span>Reklam<span class="icon-text">&#9662;</span></a>
						<a href="#" target="_blank"><img src="/assets/allegro/no-banner-728x90.jpg" alt="" /></a>
					</div>

					<div class="main-content">

						<!-- BEGIN .main-page -->
						<div class="main-page left">

							<!-- BEGIN .single-block -->
							<div class="single-block">
								
								<!-- BEGIN .content-block -->
								<div class="content-block main left">
									
									<div class="block">
										<div class="block-title">
											<%= link_to "Anasayfaya dön", root_path, class: 'right' %>
											<h2><%= @category.name %></h2>
										</div>
										<div class="block-content">
											
											<% @news.each do |news| %>
											<div class="article-big">
												<div class="article-photo">
									        <%= link_to news_path(news), class: 'hover-effect' do %>
									          <%= image_tag news.image.url(:medium), alt: news.title %>
									        <% end %>
												</div>
												<div class="article-content">
													<h2><%= link_to news.title, news_path(news) %><a href="#" class="h-comment">201</a></h2>
													<span class="meta">
														<a href="#"><span class="icon-text">&#128100;</span><%= news.user.name %></a>
														<a href="#"><span class="icon-text">&#128340;</span><%= news.created_at.to_formatted_s(:nice) %></a>
													</span>
													<p><%= news.description %></p>
													<span class="meta">
														<%= link_to news_path(news), class: 'more' do %>
														Devamını Oku<span class="icon-text">&#9656;</span>
														<% end %>
													</span>
												</div>
											</div>
											<% end %>
											
											<div class="pagination">
												<%= paginate @news %>
											</div>

										</div>
									</div>

								<!-- END .content-block -->
								</div>

							<!-- END .single-block -->
							</div>

						<!-- END .main-page -->
						</div>
						
						
						<!-- BEGIN .main-sidebar -->
						<div class="main-sidebar right">
							
							<!-- BEGIN .widget -->
							<div class="widget">
								<a href="#" target="_blank"><img src="/assets/allegro/no-banner-300x250.jpg" alt="" /></a>
								<a href="contact-us.html" class="ad-link"><span class="icon-text">&#9652;</span>Reklam<span class="icon-text">&#9652;</span></a>
							<!-- END .widget -->
							</div>
							
							<%= render 'rightbar' %>

						<!-- END .main-sidebar -->
						</div>

						<div class="clear-float"></div>

					</div>
					
				<!-- END .wrapper -->
				</div>
				
			<!-- END .content -->
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<!-- BEGIN html -->
<html lang = "en">
	<!-- BEGIN head -->
	<head>
	  <%= display_meta_tags site: 'Reuters', description: 'Reuters haber ajansı' %>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

		<!-- Meta Tags -->
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

		<!-- Favicon -->
		<link rel="shortcut icon" href="/assets/allegro/favicon.ico" type="image/x-icon" />

		<!-- Stylesheets -->
		<%= stylesheet_link_tag  'allegro/reset' %>
		<%= stylesheet_link_tag  'allegro/main-stylesheet' %>
		<%= stylesheet_link_tag  'allegro/lightbox' %>
		<%= stylesheet_link_tag  'allegro/shortcode' %>
		<%= stylesheet_link_tag  'allegro/fonts' %>
		<%= stylesheet_link_tag  'allegro/colors' %>

		<!--[if lte IE 8]>
		<link type="text/css" rel="stylesheet" href="css/ie-ancient.css" />
		<![endif]-->
		<%= stylesheet_link_tag  'allegro/responsive' %>

		<!-- Demo Only -->
		<%= stylesheet_link_tag  'allegro/demo-settings' %>

	<!-- END head -->
	</head>

	<!-- BEGIN body -->
	<body>

		<!-- BEGIN .boxed -->
		<div class="boxed">
			
			<!-- BEGIN .header -->
			<div class="header">
				
				<!-- BEGIN .wrapper -->
				<div class="wrapper">
					
					<div class="header-logo">
						<!-- <h1><a href="index.html">Allegro</a></h1> -->
						<%= link_to root_path do %>
						<img src="/assets/allegro/logo-header.gif" alt="Reuters" />
						<% end %>
					</div>
					
					<div class="header-menu">
						<ul>
							<li><a href="#">Künye</a></li>
							<li><a href="#">Reklam</a></li>
							<li><a href="#">Üye Olun</a></li>
						</ul>
						<p>Reuters haber ajansına ait yazı, resim ve haberlerin her hakkı saklıdır. İzinsiz, kaynak gösterilmeden kullanılamaz.</p>
					</div>
					
					<div class="header-addons">
						<div class="header-weather">
							<span class="report">+14°C</span>
							<img src="/assets/allegro/weather-sun-cloud.png" alt="" />
							<span class="city"><small>Bulutlu</small><b>Türkiye, Bursa</b></span>
						</div>
						<div class="header-search">
							<%= search_form_for(@search_in_site, url: search_path, method: "get") do |f| %>
								<%= f.search_field :title_or_description_cont, class: "search-input", placeholder: "Aranacak kelime.." %>
								<%= f.submit "Search", class: "search-button" %>
							<% end %>
						</div>
					</div>
					
				<!-- END .wrapper -->
				</div>

				<div class="main-menu sticky">
					
					<!-- BEGIN .wrapper -->
					<div class="wrapper">
						
						<ul class="the-menu">

							<li><%= link_to "ANASAYFA", root_path %></li>
							<li><a href="#"><span>HABERLER</span></a>
								<ul>
									<% @categories.each do |category| %>
									<li><%= link_to category.name, category_path(category) %></li>
									<% end %>
								</ul>
							</li>
							<li><a href="#">BLOG</a></li>
							<li><a href="#">VİDEO</a></li>
							<li><a href="#">FOTOĞRAF</a></li>
							<li><a href="#">ARŞİV</a></li>
							<li><a href="#">İLETİŞİM</a></li>
						</ul>

					<!-- END .wrapper -->
					</div>

				</div>

				<div class="secondary-menu">
					
					<!-- BEGIN .wrapper -->
					<div class="wrapper">
						
						<ul>
							<% @categories.each do |category| %>
							<li><%= link_to category.name, category_path(category) %></li>
							<% end %>
						</ul>

					<!-- END .wrapper -->
					</div>

				</div>
				
			<!-- END .header -->
			</div>
			
			<%= yield %>
			
			<!-- BEGIN .footer -->
			<div class="footer">
				
				<!-- BEGIN .wrapper -->
				<div class="wrapper">

					<ul class="right">
						<li><a href="#">Anasayfa</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">Video</a></li>
						<li><a href="#">Fotoğraf</a></li>
						<li><a href="#">Arşiv</a></li>
						<li><a href="#">İletişim</a></li>
					</ul>

					<%= link_to root_path, class: 'logo-footer' do %>
					<img src="/assets/allegro/logo-footer.png" alt="Reuters" />
					<% end %>
					
					<p>&copy; 2016 <b>Reuters</b> haber ajansı. Tüm hakları saklıdır.<br/>Yazılım <a href="http://www.code2.co/" target="_blank">Code2.co</a></p>
					
				<!-- END .wrapper -->
				</div>
				
			<!-- END .footer -->
			</div>
			
		<!-- END .boxed -->
		</div>

		<!-- Scripts -->
		<%= javascript_include_tag 'allegro/jquery-latest.min' %>
		<%= javascript_include_tag 'allegro/theme-scripts' %>
		<%= javascript_include_tag 'allegro/lightbox' %>
		<%#= javascript_include_tag 'allegro/demo-settings' %>

	<!-- END body -->
	</body>
<!-- END html -->
</html>

app/views/news/show.html.erb
<%#= @news.tags.all.map{|a| a.name}.split(',') %>

<%
set_meta_tags og: {
  title: @news.title,
  type: 'news',
  url: 'view-source:' + request.original_url,
  image: URI.join(request.url, @news.image.url)
}
%>

			<!-- BEGIN .content -->
			<div class="content">
				
				<!-- BEGIN .wrapper -->
				<div class="wrapper">
					
					<div class="ad-banner">
						<a href="contact-us.html" class="ad-link top"><span class="icon-text">&#9662;</span>Reklam<span class="icon-text">&#9662;</span></a>
						<a href="#" target="_blank"><img src="/assets/allegro/no-banner-728x90.jpg" alt="" /></a>
					</div>

					<div class="main-content">

						<div class="full-width">
							
							<div class="article-title">
								<div class="share-block right">
									<div>
										<div class="share-article left">
											<span>Sosyal Medya</span>
											<strong>Haberi paylaş</strong>
										</div>
										<div class="left">
											<a href="#" class="custom-soc icon-text">&#62217;</a>
											<a href="#" class="custom-soc icon-text">&#62220;</a>
											<a href="#" class="custom-soc icon-text">&#62223;</a>
											<a href="#" class="custom-soc icon-text">&#62226;</a>
											<a href="#" class="custom-soc icon-text">&#62232;</a>
										</div>
										<div class="clear-float"></div>
									</div>
									<div>
										<a href="javascript:printArticle();" class="small-button"><span class="icon-text">&#59158;</span>&nbsp;&nbsp;Haberi yazdır</a>
										<a href="#" class="small-button"><span class="icon-text">&#9993;</span>&nbsp;&nbsp;E-posta gönder</a>
									</div>
								</div>

								<h1><%= @news.title %></h1>
								<div class="author">
									<span class="hover-effect left"><%= image_tag @news.user.avatar.url(:small), alt: @news.user.name %></span>
									<div class="a-content">
										<span><b><%= @news.user.name %></b> yazdı</span>
										<span class="meta">
											<%= @news.created_at.to_formatted_s(:nice) %>
											<% if @news.created_at != @news.updated_at %>
											<span class="tag">Güncellendi</span></span>
											<% end %>
										</span>
									</div>
								</div>
							</div>

						</div>

						<!-- BEGIN .main-page -->
						<div class="main-page left">

							<!-- BEGIN .single-block -->
							<div class="single-block">
								
								<!-- BEGIN .content-block -->
								<div class="content-block main left">
									
									<div class="block">
										<div class="block-content">
												
											<p><span class="hover-effect"><%= image_tag @news.image.url(:large), alt: @news.title %></span></p>
											
											<div class="shortcode-content">

												<div class="paragraph-row">
													<div class="column3">
														<h3 class="highlight-title">İlginizi Çekebilir</h3>
														<ul>
															<% @related_news.each do |news| %>
															<li><%= link_to news.title, news_path(news) %><a href="#" class="h-comment">32</a></li>
															<% end %>
														</ul>
													</div>
													<div class="column9">
														<p><b><%= @news.description %></b></p>
														<p><%= simple_format(@news.body) %></p>
													</div>
												</div>

												<div class="article-title">
													<div class="share-block right">
														<div>
															<div class="share-article left">
																<span>Sosyal Medya</span>
																<strong>Haberi paylaş</strong>
															</div>
															<div class="left">
																<a href="#" class="custom-soc icon-text">&#62217;</a>
																<a href="#" class="custom-soc icon-text">&#62220;</a>
																<a href="#" class="custom-soc icon-text">&#62223;</a>
																<a href="#" class="custom-soc icon-text">&#62226;</a>
																<a href="#" class="custom-soc icon-text">&#62232;</a>
															</div>
															<div class="clear-float"></div>
														</div>
														<div>
															<a href="javascript:printArticle();" class="small-button"><span class="icon-text">&#59158;</span>&nbsp;&nbsp;Haberi yazdır</a>
															<a href="#" class="small-button"><span class="icon-text">&#9993;</span>&nbsp;&nbsp;E-posta gönder</a>
														</div>
													</div>

													<div class="author">
														<span class="hover-effect left"><%= image_tag @news.user.avatar.url(:small), alt: @news.user.name %></span>
														<div class="a-content">
															<span><b><%= @news.user.name %></b> yazdı</span>
															<span class="meta">
																<%= @news.created_at.to_formatted_s(:nice) %>
																<% if @news.created_at != @news.updated_at %>
																<span class="tag">Güncellendi</span></span>
																<% end %>
															</span>
														</div>
													</div>

													<div class="article-tags tag-cloud">
														<strong>ETİKETLER:</strong>
														<% @news.tags.each do |tag| %>
														<a href="#"><%= tag.name %></a>
														<% end %>
													</div>
												</div>

											</div>

										</div>

										<div class="block-title">
											<a href="#writecomment" class="right">Write a comment</a>
											<h2>4 Comments</h2>
										</div>
										<div class="block-content">

											<div class="comment-block">
												
												<ol class="comments">
													<li>
														<div class="commment-content">
															<div class="user-avatar">
																<a href="#" class="hover-effect"><img src="/assets/allegro/photos/avatar-4.jpg" class="setborder" alt="" title="" /></a>
															</div>
															<strong class="user-nick"><a href="#">Ignasi Cleto</a></strong>
															<span class="time-stamp">April 25, 12:53</span>
															<div class="comment-text">
																<p>Usu inani perfecto quaestio in, id usu paulo eruditi salutandi. In eros prompta dolores nec, ut pro causae conclusionemque. In pro elit mundi dicunt. No odio diam interpretaris pri.</p>
															</div>
															<a href="#" class="icon-link"><span class="icon-text">&#59154;</span><span>Reply to this comment</span></a>
														</div>
														<ul>
															<li>
																<div class="commment-content">
																	<div class="user-avatar">
																		<a href="#" class="hover-effect"><img src="/assets/allegro/photos/avatar-5.jpg" class="setborder" alt="" title="" /></a>
																	</div>
																	<strong class="user-nick"><a href="#">Orange-Themes</a><span class="marker">Author</span></strong>
																	<span class="time-stamp">April 25, 12:53</span>
																	<div class="comment-text">
																		<p>Ad est audire imperdiet. Cum an docendi assentior. Usu inani perfecto quaestio in, id usu paulo eruditi salutandi. In eros prompta dolores nec, ut pro causae conclusionemque. In pro elit mundi dicunt. No odio diam interpretaris pri.</p>
																	</div>
																	<a href="#" class="icon-link"><span class="icon-text">&#59154;</span><span>Reply to this comment</span></a>
																</div>
															</li>
															<li>
																<div class="commment-content">
																	<div class="user-avatar">
																		<a href="#" class="hover-effect"><img src="/assets/allegro/photos/avatar-6.jpg" class="setborder" alt="" title="" /></a>
																	</div>
																	<strong class="user-nick"><a href="#">Tatius Eugenio</a></strong>
																	<span class="time-stamp">April 25, 12:53</span>
																	<div class="comment-text">
																		<p>Has possit definiebas ne. Sed dico consul ut. Eu labore efficiantur pro. Sed legimus probatus pericula ea, cum oratio labitur concludaturque ne. Mei cu viris moderatius.</p>
																	</div>
																	<a href="#" class="icon-link"><span class="icon-text">&#59154;</span><span>Reply to this comment</span></a>
																</div>
															</li>
														</ul>
													</li>
													<li>
														<div class="commment-content">
															<div class="user-avatar">
																<span class="hover-effect"><img src="/assets/allegro/photos/avatar-7.jpg" class="setborder" alt="" title="" /></span>
															</div>
															<strong class="user-nick">Ignasi Cleto</strong>
															<span class="time-stamp">April 25, 12:53</span>
															<div class="comment-text">
																<p>Usu inani perfecto quaestio in, id usu paulo eruditi salutandi. In eros prompta dolores nec, ut pro causae conclusionemque. In pro elit mundi dicunt. No odio diam interpretaris pri.</p>
															</div>
															<a href="#" class="icon-link"><span class="icon-text">&#59154;</span><span>Reply to this comment</span></a>
														</div>
													</li>
												</ol>

											</div>

										</div>

										<div class="block-title">
											<a href="#writecomment" class="right">View all comments</a>
											<h2>Write a comment</h2>
										</div>
										<div class="block-content">
											<div id="writecomment">

												<form action="#" method="get">

													<div class="coloralert" style="background: #a12717;">
														<p>Error Occurred!</p>
														<a href="#close-alert" class="icon-text">&#10006;</a>
													</div>
													<!-- <div class="coloralert" style="background: #68a117;">
														<p>Success!</p>
														<a href="#close-alert" class="icon-text">&#10006;</a>
													</div> -->

													<p>Your e-mail address will not be published.<br/>Required fields are marked<span class="required">*</span></p>

													<p class="contact-form-user">
														<label for="c_name">Nickname<span class="required">*</span></label>
														<input type="text" class="error" placeholder="Nickname" name="c_name" id="c_name" />
														<span class="error-msg"><span class="icon-text">&#9888;</span>&nbsp;&nbsp;This is an error message</span>
													</p>
													<p class="contact-form-email">
														<label for="c_email">E-mail<span class="required">*</span></label>
														<input type="text" placeholder="E-mail" name="c_email" id="c_email" />
													</p>
													<p class="contact-form-webside">
														<label for="c_webside">Website</label>
														<input type="text" placeholder="Website" name="c_webside" id="c_webside" />
													</p>
													<p class="contact-form-message">
														<label for="c_message">Comment<span class="required">*</span></label>
														<textarea name="c_message" placeholder="Your message.." id="c_message"></textarea>
													</p>
													<p><input type="submit" class="styled-button" value="Post a Comment" /></p>
												</form>
												
											</div>
										</div>

									</div>

								<!-- END .content-block -->
								</div>

							<!-- END .single-block -->
							</div>

						<!-- END .main-page -->
						</div>
						
						<!-- BEGIN .main-sidebar -->
						<div class="main-sidebar right">
							
							<!-- BEGIN .widget -->
							<div class="widget">
								<a href="#" target="_blank"><img src="/assets/allegro/no-banner-300x250.jpg" alt="" /></a>
								<a href="contact-us.html" class="ad-link"><span class="icon-text">&#9652;</span>Advertisement<span class="icon-text">&#9652;</span></a>
							<!-- END .widget -->
							</div>
							
							<%= render 'rightbar' %>

						<!-- END .main-sidebar -->
						</div>

						<div class="clear-float"></div>

					</div>
					
				<!-- END .wrapper -->
				</div>
				
			<!-- END .content -->
			</div>